name: basics
env:
  APPLICATION_NAME: "MyFlask"
  PACKAGE_NAME: "flask-deploy-ver-${{ github.sha }}"

on:
  push:
    branches:
      - master

jobs:
  my_testing:
    runs-on: ubuntu-latest

    steps:
      - name: Print Hello Message in Testing
        run: echo "Hello World from Testing job"

      - name: Execute few commands
        run: |
          echo "Hello Message1"
          echo "Hello Message2"
          echo "Application Name: ${{ env.APPLICATION_NAME }}"

      - name: List current folder
        run: ls -la

  my_deploy:
    runs-on: ubuntu-latest
    needs: my_testing

    steps:
      - name: Print Hello Message in Deploy
        run: echo "Hello World from Deploy job"

      - name: Printing Deployment package
        run: echo "Deploy package name is ${{ env.PACKAGE_NAME }}"
